//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UploadImagesInMVC.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.Web;

    public partial class Image
    {// The first three queries are already define d in database
        public int ImageId { get; set; }
        public string Title { get; set; }
        [DisplayName("Upload Image")]
        public string ImagePath { get; set; }
        //This query i've added after connecting with model database.
        public HttpPostedFileBase ImageFile { get; set; }
    }
}
